[project]
name = "kleister-nda-preprocessing"
version = "0.1.0"
requires-python = ">=3.13.3"
dependencies = [
    "pandas>=3.0.1",
    "polars>=1.38.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
